include: package:flutter_lints/flutter.yaml

analyzer:
  # 🚀 FORCES THE COMPILER TO IGNORE INTERACTION STYLE WARNINGS IN CI PIPELINES
  errors:
    todo: ignore
    invalid_annotation_target: ignore
    missing_required_param: ignore
    
  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # 🚀 DISABLES THE STRICT CONTROLS THAT CRASH FLUTTER ANALYZE IN GITHUB ACTIONS
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_values: false
    always_specify_types: false
    avoid_print: false
    unused_import: false
    unused_local_variable: false
