name: mind_spark
description: "AI TUTOR & AR LAB"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter: { sdk: flutter }
  provider:
  supabase_flutter:
  flutter_dotenv:
  dio:
  arcore_flutter_plus:
  vector_math:
  flutter_animate:
  google_mobile_ads:
  intl:
  permission_handler:

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints:
  flutter_launcher_icons:
  build_runner:

flutter:
  uses-material-design: true
  assets: ["assets/images/"]
  fonts:
    - family: Inter
      fonts: [{asset: "assets/fonts/Inter-Regular.ttf"}, {asset: "assets/fonts/Inter-Bold.ttf", weight: 700}]

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app_icon.png"
