name: mindspark1
description: "AI TUTOR & AR LAB"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2

  # Backend
  supabase_flutter: ^2.6.0

  # Environment
  flutter_dotenv: ^6.0.1

  # Networking
  dio: ^5.5.0

  # Utilities
  intl: ^0.19.0
  crypto: ^3.0.5
  uuid: ^4.4.0
  vector_math: ^2.1.4

  # Device
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  url_launcher: ^6.3.0

  # AI
  google_generative_ai: ^0.4.2

  # Voice
  flutter_tts: ^4.2.5
  speech_to_text: ^7.4.0

  # Animation
  flutter_animate: ^4.5.0

  # Camera & Vision
  camera: ^0.11.0
  google_mlkit_face_detection: ^0.12.0

  # WebRTC
  flutter_webrtc: ^1.2.0

  # Deep Links
  app_links: ^6.3.2

  # WebView
  webview_flutter: ^4.9.0

  # Ads
  google_mobile_ads: ^5.2.0

  # AR (Android)
  arcore_flutter_plus: ^1.0.2

  device_info_plus: any
  google_mlkit_language_id: any
  google_translate_api: any
  in_app_review: any
  flutter_tex: any
  http: any
  hive_flutter: any
  flutter_secure_storage: any
  freerasp: any
  pdf: any
  ntp: any
  audioplayers: any
  dart_openai: any
  cloud_firestore: any
  flutter_math_fork: any
  google_mlkit_text_recognition: any
  groq_sdk: any
  firebase_auth: any
  qr_flutter: any
  share_plus: any
  connectivity_plus: any
  sks_ticket_view: any
  vibration: any
  audio_session: any
  environment_sensors: any
  pqcrypto: any
  thirds: any
  safe_device: any
  flutter_jailbreak_detection: any
  firebase_analytics: any
  in_app_purchase: any
  flutter_cache_manager: any
  battery_plus: any
  image_picker: any
  package_info_plus: any
  carrier_info: any
  video_player: any
  sqflite: any
  path: any
  google_sign_in: any
  flutter_image_compress: any
  flutter_windowmanager: any
  ios_insecure_screen_detector: any
  firebase_messaging: any
  flutter_local_notifications: any
  timezone: any
  sensors_plus: any
  drift: any
  model_viewer_plus: any
  file_picker: any
  flutter_fortune_wheel: any
  screen_brightness: any
  dash_chat_2: any
  pointycastle: any
  flutter_highlight: any
  shimmer: any
  local_auth: any
  cached_network_image: any
  confetti: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  source_gen: ^1.5.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: assets/icon_launcher.png

  web:
    generate: true
    image_path: assets/icon_launcher.png
