import 'dart:io';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

class PdfExporter {
  static Future<void> exportLesson(String topic, String content) async {
    final pdf = pw.Document();
    pdf.addPage(pw.Page(
      build: (ctx) => pw.Column(children: [
        pw.Text(topic, style: pw.TextStyle(fontSize: 24)),
        pw.Paragraph(text: content),
        pw.Footer(title: pw.Text("Generated by Mind Spark"))
      ])
    ));

    final dir = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/$topic.pdf');
    await file.writeAsBytes(await pdf.save());
    Share.shareXFiles([XFile(file.path)], text: "My Revision Notes");
  }
}