android.useAndroidX=true
android.enableJetifier=true

# Optimization properties for compiling your massive list of heavy-weight native plugins
org.gradle.jvmargs=-Xmx4g -XX:+UseParallelGC -XX:MaxMetaspaceSize=512m
org.gradle.workers.max=4
android.enableR8.fullMode=false

systemProp.org.gradle.internal.kotlin.build.tools.api.enabled=false
kotlin.compiler.execution.strategy=in-process
org.gradle.dependency.verification=off
android.defaults.buildfeatures.buildconfig=true
