# 🚀 FORCE DEACTIVATION OF THE BUGGY BUILD TOOLS API COMPILATION PIPELINE
systemProp.org.gradle.internal.kotlin.build.tools.api.enabled=false
android.experimental.runCompileKotlinAsTask=true
kotlin.compiler.execution.strategy=in-process

# 🚀 CLEAR DOWN ARTIFACT OVERRIDE MAPS NATIVELY
org.gradle.dependency.verification=off
